# Generated by Django 3.2.8 on 2021-10-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(help_text='Unique Id to identify a workspace', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the workspace', max_length=255)),
                ('fyle_org_id', models.CharField(help_text='org id', max_length=255, unique=True)),
                ('last_synced_at', models.DateTimeField(help_text='Datetime when expenses were pulled last', null=True)),
                ('source_synced_at', models.DateTimeField(help_text='Datetime when source dimensions were pulled', null=True)),
                ('destination_synced_at', models.DateTimeField(help_text='Datetime when destination dimensions were pulled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created at datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated at datetime')),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
    ]
