# Generated by Django 3.2.8 on 2021-10-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("insert into workspaces "
        "(name, fyle_org_id, created_at, updated_at) values "
        "('Fyle', 'dummyOrgId', date('now'), date('now'))")
    ]
